# Generated by Django 5.0.2 on 2024-03-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_profesor_carrera_profesor_year'),
        ('profesor', '0003_profesor_rating'),
    ]

    operations = [
    ]
