# Generated by Django 4.2.7 on 2024-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0005_carrera_remove_profesor_carrera_profesor_carreers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
