# Generated by Django 4.2.7 on 2024-04-29 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profesor', '0007_remove_profesor_rating_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesor.profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('usuario', 'profesor')},
        ),
    ]
