# Generated by Django 5.0.2 on 2024-05-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0008_voto_profesor_alter_voto_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='image',
            field=models.ImageField(default='profesor/images/defaultt.jpg', upload_to='profesor/images/'),
        ),
    ]
