# Generated by Django 5.0.2 on 2024-05-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0009_profesor_education_alter_profesor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
