# Generated by Django 5.0.2 on 2024-05-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0010_profesor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
