# Generated by Django 5.0.2 on 2024-05-13 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0012_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(200), django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
