# Generated by Django 5.0.2 on 2024-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_profesor_genre_profesor_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
