# Generated by Django 5.0.2 on 2024-05-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
        ('profesor', '0009_profesor_education_alter_profesor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='profesor.profesor'),
        ),
    ]
