# Generated by Django 5.0.2 on 2024-05-12 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticias_author'),
        ('profesor', '0009_profesor_education_alter_profesor_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='author',
        ),
        migrations.AddField(
            model_name='noticias',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='profesor.profesor'),
        ),
    ]
