# Generated by Django 4.2.7 on 2024-03-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=100)),
                ('calificacion', models.CharField(max_length=3)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
