# Generated by Django 4.2.7 on 2024-03-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='calificacion',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='materia',
            field=models.TextField(max_length=100),
        ),
    ]
